version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: disabled
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: "/cdk"
    schedule:
      interval: weekly
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: "/tests/e2e"
    schedule:
      interval: weekly
    rebase-strategy: disabled
